version: "3.7"

services:
  # backend-api:
  #   build:
  #     context: backend/.
  #     dockerfile: Dockerfile
  #   container_name: go-backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - "postgres"
  postgres:
    image: postgres:15.4-alpine
    container_name: "psql-db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # frontend:
  #   build:
  #     context: frontend/.
  #     dockerfile: Dockerfile
  #   container_name: preact-frontend
  #   ports:
  #     - "5173:5173"
