version: "3"
services:
  mongodb-primary:
    container_name: mongodb-primary
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./mongdb/mongodb-volumes
        target: /mongodb-volumes/db-primary
