version: "3.7"

services:
  postgres:
    image: postgres:15.4-alpine
    container_name: "psql-db"
    restart: always
    environment:
      POSTGRES_USER: $PSQL_USER
      POSTGRES_PASSWORD: $PSQL_PASSWORD
      POSTGRES_DB: $PSQL_DBNAME
    ports:
      - $PSQL_PORT:$PSQL_PORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
