version: "3.7"

services:
  primary-mongo:
    image: mongo:latest
    container_name: primary-mongo
    networks:
      - mongo-cluster
    ports:
      - $MDB_PRIMARY_PORT:27017
    volumes:
      - ./primary:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    entrypoint: ["/bin/bash", "config/init-replication.sh"]

  replica-mongo:
    image: mongo:latest
    container_name: replica-mongo
    networks:
      - mongo-cluster
    ports:
      - $MDB_SECONDARY_PORT:27017
    volumes:
      - ./replica:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password

networks:
  mongo-cluster:
    driver: bridge
